### ISSUE TITLE
Installation fails in Node v0.12 and io.js

### ISSUE THREAD

**Issue by MartijnR** [bsuh/node_xslt#24]
```
make: *** [Release/obj.target/node_xslt/node_xslt.o] Error 1
make: Leaving directory `/home/enketo/test/node_modules/node_xslt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/enketo/test/node_modules/node_xslt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node_xslt"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node_xslt@0.1.9 preinstall: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node_xslt@0.1.9 preinstall script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node_xslt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node_xslt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/enketo/test/npm-debug.log
```

**Comment by kildem** [comment]
installation fails in Node v0.12

**Comment by CentaurWarchief** [comment]
@kildem 

Can you provide more details?
Thanks.

**Comment by kildem** [comment]
I have update node from version 10 to 12:
this is the log file:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '--save', 'node_xslt' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 warn package.json nan@1.6.2 No README data
5 silly cache add args [ 'node_xslt', null ]
6 verbose cache add spec node_xslt
7 silly cache add parsed spec { raw: 'node_xslt',
7 silly cache add   scope: null,
7 silly cache add   name: 'node_xslt',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed node_xslt@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'node_xslt', range: '*', hasData: false }
12 silly mapToRegistry name node_xslt
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/node_xslt
16 verbose addNameRange registry:https://registry.npmjs.org/node_xslt not in flight; fetching
17 verbose request uri https://registry.npmjs.org/node_xslt
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:02:48 PM
20 verbose request id fa14e129ade61487
21 verbose etag "1XQRL1MEHOR6O3CPW4D5KCT4Z"
22 http request GET https://registry.npmjs.org/node_xslt
23 http 304 https://registry.npmjs.org/node_xslt
24 silly get cb [ 304,
24 silly get   { date: 'Mon, 16 Feb 2015 12:02:48 GMT',
24 silly get     server: 'Apache',
24 silly get     via: '1.1 varnish',
24 silly get     'last-modified': 'Mon, 16 Feb 2015 12:02:49 GMT',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"1XQRL1MEHOR6O3CPW4D5KCT4Z"',
24 silly get     age: '0',
24 silly get     'x-served-by': 'cache-lhr6321-LHR',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1424088168.786333,VS0,VE373',
24 silly get     vary: 'Accept',
24 silly get     'content-length': '0',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose etag https://registry.npmjs.org/node_xslt from cache
26 verbose get saving node_xslt to /Users/ilde/.npm/registry.npmjs.org/node_xslt/.cache.json
27 silly addNameRange number 2 { name: 'node_xslt', range: '*', hasData: true }
28 silly addNameRange versions [ 'node_xslt',
28 silly addNameRange   [ '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9' ] ]
29 verbose addNamed node_xslt@0.1.9
30 silly addNamed semver.valid 0.1.9
31 silly addNamed semver.validRange 0.1.9
32 silly cache afterAdd node_xslt@0.1.9
33 verbose afterAdd /Users/ilde/.npm/node_xslt/0.1.9/package/package.json not in flight; writing
34 verbose afterAdd /Users/ilde/.npm/node_xslt/0.1.9/package/package.json written
35 silly install resolved [ { name: 'node_xslt',
35 silly install resolved     version: '0.1.9',
35 silly install resolved     main: './build/Release/node_xslt',
35 silly install resolved     engines: { node: '>=0.1.93' },
35 silly install resolved     dependencies: {},
35 silly install resolved     scripts: { preinstall: 'node-gyp rebuild' },
35 silly install resolved     description: 'A simple XSLT package for node.js',
35 silly install resolved     author: { name: 'Brian Suh', email: 'brian.j.suh@gmail.com' },
35 silly install resolved     homepage: 'https://github.com/bsuh/node_xslt',
35 silly install resolved     repository: { type: 'git', url: 'git://github.com/bsuh/node_xslt.git' },
35 silly install resolved     readme: '# node_xslt\n\n    xslt = require(\'node_xslt\')\n\n    stylesheet = xslt.readXsltString(string);\n    // readXsltString\n    // Arguments: string containing XSLT\n    // Returns: stylesheet object\n\n    stylesheet = xslt.readXsltFile(filename);\n    // readXsltFile\n    // Arguments: filename to file containing XSLT\n    // Returns: stylesheet object\n\n    document = xslt.readXmlString(string);\n    // readXmlString\n    // Arguments: string containing XML\n    // Returns: document object\n\n    document = xslt.readXmlFile(filename);\n    // readXmlFile\n    // Arguments: filename to file containing XML\n    // Returns: document object\n\n    htmlDocument = xslt.readHtmlString(string);\n    // readHtmlString\n    // Arguments: string containing HTML\n    // Returns: document object\n\n    htmlDocument = xslt.readHtmlFile(string);\n    // readHtmlFile\n    // Arguments: filename to file containing HTML\n    // Returns: document object\n    \n    transformedString = xslt.transform(stylesheet, document, parameters);\n    // transform\n    // Arguments:\n    //  * stylesheet: stylesheet object\n    //  * document: document object\n    //  * parameters: an array of parameters to be passed to the stylesheet. length must be multiple of 2.\n    //        Example: [\'param1Name\', \'param1Value\', \'param2Name\', \'param2Value\']\n\n## Requirements\n\n* [libxml2](http://www.xmlsoft.org/) (libxml2-dev package for Debian-based distros)\n* [libxslt](http://xmlsoft.org/xslt/index.html) (libxslt-dev package for Debian-based distros)\n* [libexslt](http://xmlsoft.org/xslt/EXSLT/) (libxslt-dev package for Debian-based distros)\n* xml2-config (Needs to be on PATH)\n\n## Installation\n\n**npm**\n\n    npm install node_xslt\n\n**source**\n\n    In the root directory, run `node-gyp rebuild` to generate\n    ./build/Release/node_xslt.node\n',
35 silly install resolved     readmeFilename: 'README.md',
35 silly install resolved     bugs: { url: 'https://github.com/bsuh/node_xslt/issues' },
35 silly install resolved     _id: 'node_xslt@0.1.9',
35 silly install resolved     dist:
35 silly install resolved      { shasum: 'ad01c7d57ca5563294717ac0ce7604b77bc032f1',
35 silly install resolved        tarball: 'http://registry.npmjs.org/node_xslt/-/node_xslt-0.1.9.tgz' },
35 silly install resolved     _from: 'node_xslt@*',
35 silly install resolved     _npmVersion: '1.3.5',
35 silly install resolved     _npmUser: { name: 'bahblah', email: 'brian.j.suh@gmail.com' },
35 silly install resolved     maintainers: [ [Object] ],
35 silly install resolved     directories: {},
35 silly install resolved     _shasum: 'ad01c7d57ca5563294717ac0ce7604b77bc032f1',
35 silly install resolved     _resolved: 'https://registry.npmjs.org/node_xslt/-/node_xslt-0.1.9.tgz' } ]
36 info install node_xslt@0.1.9 into /Users/ilde/..
37 info installOne node_xslt@0.1.9
38 verbose installOne of node_xslt to /Users/ilde/.. not in flight; installing
39 verbose lock using /Users/ilde/.npm/_locks/node-xslt-009641292e9d9ece.lock for /Users/ilde/../node_modules/node_xslt
40 silly install write writing node_xslt 0.1.9 to /Users/ilde/../node_modules/node_xslt
41 silly cache addNamed cb node_xslt@0.1.9
42 verbose unbuild node_modules/node_xslt
43 verbose gentlyRm vacuuming /Users/ilde/../node_modules/node_xslt
44 verbose tar unpack /Users/ilde/.npm/node_xslt/0.1.9/package.tgz
45 verbose tar unpacking to /Users/ilde/../node_modules/node_xslt
46 verbose gentlyRm vacuuming /Users/ilde/../node_modules/node_xslt
47 silly gunzTarPerm modes [ '755', '644' ]
48 silly gunzTarPerm extractEntry package.json
49 silly gunzTarPerm extractEntry .npmignore
50 silly gunzTarPerm extractEntry README.md
51 silly gunzTarPerm extractEntry binding.gyp
52 silly gunzTarPerm extractEntry .binding.gyp.un~
53 silly gunzTarPerm extractEntry .package.json.un~
54 silly gunzTarPerm extractEntry macros.h
55 silly gunzTarPerm extractEntry node_xslt.cc
56 silly gunzTarPerm extractEntry LICENSE.txt
57 silly gunzTarPerm extractEntry scopeguard.h
58 silly gunzTarPerm extractEntry wscript
59 info preinstall node_xslt@0.1.9
60 verbose unsafe-perm in lifecycle true
61 info node_xslt@0.1.9 Failed to exec preinstall script
62 verbose unlock done using /Users/ilde/.npm/_locks/node-xslt-009641292e9d9ece.lock for /Users/ilde/../node_modules/node_xslt
63 verbose stack Error: node_xslt@0.1.9 preinstall: `node-gyp rebuild`
63 verbose stack Exit status 1
63 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
63 verbose stack     at EventEmitter.emit (events.js:110:17)
63 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
63 verbose stack     at ChildProcess.emit (events.js:110:17)
63 verbose stack     at maybeClose (child_process.js:1008:16)
63 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
64 verbose pkgid node_xslt@0.1.9
65 verbose cwd /Users/ilde/..
66 error Darwin 14.1.0
67 error argv "node" "/usr/local/bin/npm" "install" "--save" "node_xslt"
68 error node v0.12.0
69 error npm  v2.5.1
70 error code ELIFECYCLE
71 error node_xslt@0.1.9 preinstall: `node-gyp rebuild`
71 error Exit status 1
72 error Failed at the node_xslt@0.1.9 preinstall script 'node-gyp rebuild'.
72 error This is most likely a problem with the node_xslt package,
72 error not with npm itself.
72 error Tell the author that this fails on your system:
72 error     node-gyp rebuild
72 error You can get their info via:
72 error     npm owner ls node_xslt
72 error There is likely additional logging output above.
73 verbose exit [ 1, true ]
74 verbose unbuild node_modules/node_xslt
75 info preuninstall node_xslt@0.1.9
76 info uninstall node_xslt@0.1.9
77 verbose unbuild rmStuff node_xslt@0.1.9 from /Users/ilde/../node_modules
78 info postuninstall node_xslt@0.1.9
79 verbose gentlyRm vacuuming /Users/ilde/../node_modules/node_xslt
80 silly gentlyRm purging /Users/ilde/../node_modules/node_xslt
81 silly gentlyRm quitting because other entries in /Users/ilde/../node_modules

**Comment by CentaurWarchief** [comment]
Well, I'll have to dive into some sort of debugging, as I can't reproduce this easily.

**Comment by kildem** [comment]
if I switch to node v0.10.9 I can install node_xslt and the app works, but if I switch back to node v.0.12 
it doesn't run

**Comment by MartijnR** [comment]
I'm guessing it's the same issue as with 0.11 => https://github.com/bsuh/node_xslt/issues/24

**Comment by MartijnR** [comment]
Updated the title. Similar build error now also shown on 0.10.37 now, so that makes it a bit more serious.

Would anybody be able to fix this perhaps?

```
enketo@enketo-core-performance-monitor:~/test$ npm install node_xslt
npm WARN package.json nodejs@0.0.0 No description
npm WARN package.json nodejs@0.0.0 No repository field.
npm WARN package.json nodejs@0.0.0 No README data

> node_xslt@0.1.9 preinstall /home/enketo/test/node_modules/node_xslt
> node-gyp rebuild

/bin/sh: 1: xml2-config: not found
gyp: Call to 'xml2-config --cflags' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/enketo/test/node_modules/node_xslt
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! node_xslt@0.1.9 preinstall: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node_xslt@0.1.9 preinstall script.
npm ERR! This is most likely a problem with the node_xslt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node_xslt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node_xslt"
npm ERR! cwd /home/enketo/test
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by MartijnR** [comment]
@CentaurWarchief Are you able to install this on node 0.12?

 If so how do you install the prerequisites? I use `apt-get install libxml2-dev libxslt1-dev`.

I updated the error log with the 0.12 in the top post.

**Comment by CentaurWarchief** [comment]
@MartijnR didn't tried it out yet. I'll do it later when I find time for - currently - I'm stuck :(

**Comment by MartijnR** [comment]
thanks!

**Comment by MartijnR** [comment]
Imho we don't need to maintain compatibility with node v0.10.x in a new version of this library. Any thoughts on that? That might simplify the fix.

**Comment by zeroedin** [comment]
+1 for installation on Node v0.12.

**Comment by alxndrsn** [comment]
Any update on support for node 0.12.x?

**Comment by MartijnR** [comment]
This will offer much better hope for node 0.12 support: https://github.com/albanm/node-libxslt (though currently it is not working for me either on node 0.12.6, the repo and its main dependency (libxmljs) are under active development.

**Comment by kildem** [comment]
I've switched to xslt4node and it works fine with node v0.12
https://www.npmjs.com/package/xslt4node

**Comment by MartijnR** [comment]
update: https://github.com/albanm/node-libxslt supports NodeJS 0.12, v4.x and v5.x now (and no Java!)
