### ISSUE TITLE
windows - xml2-config not recognized

### ISSUE THREAD

**Issue by christopher5106** [bsuh/node_xslt#29]
Here is an error I get on Windows 

```
'xml2-config' n'est pas reconnu en tant que commande interne

ou externe, un programme ex‚cutable ou un fichier de commandes.

gyp: Call to 'xml2-config --cflags' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\user\apps\catalog-scala-ADMIN\src\main\node\node_modules\node_xslt
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! node_xslt@0.1.9 preinstall: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node_xslt@0.1.9 preinstall script.
npm ERR! This is most likely a problem with the node_xslt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node_xslt
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "node_xslt"
npm ERR! cwd c:\Users\user\apps\catalog-scala-ADMIN\src\main\node
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by rainabba** [comment]
Developer states in the README that this has Debian dependencies so it's not for Windows use. I'm looking for something myself.

**Comment by christopher5106** [comment]
Ok thanks for your answer
In my case, I've been using directly 'xsltproc' command and 'awk' in other cases... so it's multi platforms.

**Comment by rainabba** [comment]
@christopher5106 Couple days in, not tested in an isolated, production environment (like Modulus or Heroku), but so far [xslt4node](https://www.npmjs.com/package/xslt4node) is working well for me.

**Comment by christopher5106** [comment]
ok great thank you!
