### ISSUE TITLE
Problems to install on Mac OSX 10.11.5 and Node v4.2.2

### ISSUE THREAD

**Issue by clbaeza** [bsuh/node_xslt#31]
Hi, I try to install but error in build fase.
Here the log

npm install node_xslt
|

> node_xslt@0.1.9 preinstall /Users/claudiobaeza/Desarrollos/AGESIC/codeV3/node_pacs/dicom_send/node_modules/node_xslt
> node-gyp rebuild

  CXX(target) Release/obj.target/node_xslt/node_xslt.o
../node_xslt.cc:18:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope handlescope;
                ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node_xslt.cc:19:30: error: member reference type 'Persistentv8::Value' is not a pointer; did you mean to use '.'?
    Local<Object> obj = value->ToObject();
                        ~~~~~^~
                             .
../node_xslt.cc:19:32: error: no member named 'ToObject' in 'v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >'
    Local<Object> obj = value->ToObject();
                        ~~~~~  ^
../node_xslt.cc:26:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope handlescope;
                ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node_xslt.cc:27:30: error: member reference type 'Persistentv8::Value' is not a pointer; did you mean to use '.'?
    Local<Object> obj = value->ToObject();
                        ~~~~~^~
                             .
../node_xslt.cc:27:32: error: no member named 'ToObject' in 'v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >'
    Local<Object> obj = value->ToObject();
                        ~~~~~  ^
../node_xslt.cc:33:1: error: calling a protected constructor of class 'v8::HandleScope'
OBJECT(jsXmlDoc, 1, xmlDocPtr doc)
^
../macros.h:133:21: note: expanded from macro 'OBJECT'
    v8::HandleScope handlescope;\
                    ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node_xslt.cc:33:1: error: too few arguments to function call, at least argument 'isolate' must be specified
OBJECT(jsXmlDoc, 1, xmlDocPtr doc)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../macros.h:134:79: note: expanded from macro 'OBJECT'
    v8::Handlev8::FunctionTemplate   **class**  = v8::FunctionTemplate::New();\
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:4349:3: note: 'New' declared here
  static Local<FunctionTemplate> New(
  ^
../node_xslt.cc:34:5: error: too few arguments to function call, expected 2, have 1
    INTERNAL(0, doc)
    ^~~~~~~~~~~~~~~~
../macros.h:156:61: note: expanded from macro 'INTERNAL'
    self->SetInternalField(i, v8::External::New((void_)value));
                              ~~~~~~~~~~~~~~~~~             ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:4003:3: note: 'New' declared here
  static Local<External> New(Isolate_ isolate, void\* value);
  ^
../node_xslt.cc:35:5: error: too few arguments to function call, expected 2, have 1
    OBJ_DESTRUCTOR(&jsXmlDocCleanup)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_xslt.cc:12:89: note: expanded from macro 'OBJ_DESTRUCTOR'
# define OBJ_DESTRUCTOR(d) Persistent<Object> _weak_handle = Persistent<Object>::New(self); \

```
                                                        ~~~~~~~~~~~~~~~~~~~~~~~     ^
```

/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:639:3: note: 'New' declared here
  V8_INLINE static T\* New(Isolate\* isolate, T\* that);
  ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8config.h:301:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline **attribute**((always_inline))

```
               ^
```

../node_xslt.cc:35:5: error: 'New' is a private member of 'v8::PersistentBasev8::Object'
    OBJ_DESTRUCTOR(&jsXmlDocCleanup)
    ^
../node_xslt.cc:12:81: note: expanded from macro 'OBJ_DESTRUCTOR'
# define OBJ_DESTRUCTOR(d) Persistent<Object> _weak_handle = Persistent<Object>::New(self); \

```
                                                                            ^
```

/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:639:23: note: declared private here
  V8_INLINE static T\* New(Isolate\* isolate, T\* that);
                      ^
../node_xslt.cc:35:5: error: no member named 'MakeWeak' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    OBJ_DESTRUCTOR(&jsXmlDocCleanup)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_xslt.cc:13:40: note: expanded from macro 'OBJ_DESTRUCTOR'
                          _weak_handle.MakeWeak(NULL, d);
                          ~~~~~~~~~~~~ ^
../node_xslt.cc:36:5: error: no member named 'Close' in 'v8::HandleScope'
    RETURN_SCOPED(self);
    ^~~~~~~~~~~~~~~~~~~
../macros.h:112:52: note: expanded from macro 'RETURN_SCOPED'
# define RETURN_SCOPED(x)        return handlescope.Close(x)

```
                                   ~~~~~~~~~~~ ^
```

../node_xslt.cc:39:1: error: calling a protected constructor of class 'v8::HandleScope'
OBJECT(jsXsltStylesheet, 1, xsltStylesheetPtr style)
^
../macros.h:133:21: note: expanded from macro 'OBJECT'
    v8::HandleScope handlescope;\
                    ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node_xslt.cc:39:1: error: too few arguments to function call, at least argument 'isolate' must be specified
OBJECT(jsXsltStylesheet, 1, xsltStylesheetPtr style)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../macros.h:134:79: note: expanded from macro 'OBJECT'
    v8::Handlev8::FunctionTemplate   **class**  = v8::FunctionTemplate::New();\
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:4349:3: note: 'New' declared here
  static Local<FunctionTemplate> New(
  ^
../node_xslt.cc:40:5: error: too few arguments to function call, expected 2, have 1
    INTERNAL(0, style)
    ^~~~~~~~~~~~~~~~~~
../macros.h:156:61: note: expanded from macro 'INTERNAL'
    self->SetInternalField(i, v8::External::New((void_)value));
                              ~~~~~~~~~~~~~~~~~             ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:4003:3: note: 'New' declared here
  static Local<External> New(Isolate_ isolate, void\* value);
  ^
../node_xslt.cc:41:5: error: too few arguments to function call, expected 2, have 1
    OBJ_DESTRUCTOR(&jsXsltStylesheetCleanup)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_xslt.cc:12:89: note: expanded from macro 'OBJ_DESTRUCTOR'
# define OBJ_DESTRUCTOR(d) Persistent<Object> _weak_handle = Persistent<Object>::New(self); \

```
                                                        ~~~~~~~~~~~~~~~~~~~~~~~     ^
```

/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:639:3: note: 'New' declared here
  V8_INLINE static T\* New(Isolate\* isolate, T\* that);
  ^
/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8config.h:301:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline **attribute**((always_inline))

```
               ^
```

../node_xslt.cc:41:5: error: 'New' is a private member of 'v8::PersistentBasev8::Object'
    OBJ_DESTRUCTOR(&jsXsltStylesheetCleanup)
    ^
../node_xslt.cc:12:81: note: expanded from macro 'OBJ_DESTRUCTOR'
# define OBJ_DESTRUCTOR(d) Persistent<Object> _weak_handle = Persistent<Object>::New(self); \

```
                                                                            ^
```

/Users/claudiobaeza/.node-gyp/4.2.2/include/node/v8.h:639:23: note: declared private here
  V8_INLINE static T\* New(Isolate\* isolate, T\* that);
                      ^
../node_xslt.cc:41:5: error: no member named 'MakeWeak' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    OBJ_DESTRUCTOR(&jsXsltStylesheetCleanup)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_xslt.cc:13:40: note: expanded from macro 'OBJ_DESTRUCTOR'
                          _weak_handle.MakeWeak(NULL, d);
                          ~~~~~~~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: **\* [Release/obj.target/node_xslt/node_xslt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/claudiobaeza/Desarrollos/AGESIC/codeV3/node_pacs/dicom_send/node_modules/node_xslt
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node_xslt"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node_xslt@0.1.9 preinstall: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node_xslt@0.1.9 preinstall script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node_xslt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node_xslt
npm ERR! There is likely additional logging output above.

**Comment by bsuh** [comment]
I haven't worked on this package for a long time. I would suggest looking at some other packages like xslt4node or node-libxslt.

**Comment by clbaeza** [comment]
Ok, thanks for the reply.
